### PR TITLE
Use custom pool struct to allow proper database selection

### PR DESCRIPTION
**Pull request by MorpheusXAUT**
I've been playing around with your session store for a bit now and used it successfully in one application, however recently started working on a second web app, which also shares the same redis instance.
For this reason, I've tried using your NewRediStoreWithDB function to select different databases, only to realise that both apps were still using the same (default) database "0".

After some digging and trying around, I've noticed that apparently performing the "SELECT" command in the pool dial function is **not** enough to select the proper database for all subsequent connections retrieved from the pool. For this reason, I've written a custom "RedisPool" that implements the redis.Pool struct you have been using, but stores the selected database name and performs a "SELECT" command for every connection-get request.

I hope this change works for you and fits your requirements, I'm happy to make some other changes if you'd like.

### CODE REVIEW

**Comment by boj** [comment]
@MorpheusXAUT This looks good.  If you could add a test which handles the database selection I'll merge this in.

**Comment by MorpheusXAUT** [comment]
Sure, I'll get onto adding a small test for it tomorrow or on Thursday, depending on my work schedule.

**Comment by boj** [comment]
Please check merged PR #17 - it may have addressed this issue with minimal code changes.

**Comment by MorpheusXAUT** [comment]
Firstly, sorry for not following up on the unit tests - I got busy and forgot about that.
Seems like the merged PR works fine and solves the problems I was noticing, thanks for that :smile:
Closing this pull request since the issue has been solved in master.

**Pull request closed without merging**
