### PR TITLE
Redis session backend for high scale

### PR DESCRIPTION
**Pull request by vishal24tuniki**
- Using redis cluster for high traffic sites

### CODE REVIEW

**Comment by boj** [comment]
Does anyone still actively using this library want to give this branch a shot? I'm reluctant to merge it in without feedback from other users.

**Comment by elithrar** [comment]
My concern here is that this adds a reasonably large dependency for others, even if not using Redis Cluster, as it requires a different Redis client library.

The code otherwise looks good at an initial first pass.

PS: Great avatar @boj!

**Comment by vishal24tuniki** [comment]
@boj I see this project as the best one for sessions backend using redis. No doubt that this would be the project being used actively.
I thought this PR would solve the only caveat i.e., a standalone redis wouldn't hold high traffic sites, hence have an option for using redis cluster backend

**Comment by kisielk** [comment]
IMO it would be better to make a new version of the package entirely, or just create a new package, and use only the `gopkg.in/redis` library (also any reason you're not using v6 instead of v5?). It's a pretty large additional dependency, and not everyone will need it. The implementation of the store would also be nicer if it didn't have to switch between two different libraries, you could use an interface to switch between `redis.Client` and `redis.ClusterClient` and simplify the implementation quite a bit.

Anyway, that's my 2c.

**Comment by vishal24tuniki** [comment]
@kisielk @elithrar I understand your point of view. Alternatively i can make the change to complete use `gopkg.in/redis` library alone instead of 2 different clients (1 of standalone and 1 for cluster). No reason in particular for using `v5` instead of `v6`. Probably when i forked the repo, there wasn't `v6`

This seems to be a proper way. Would like to have @boj opinion before the change. In any case i will test the library by completely switching to `gopkg.in/redis` with `v6` version and keep this thread updated

**Comment by boj** [comment]
@vishal24tuniki I honestly don't have much of an opinion on this library these days as I don't use it. Deferring to @elithrar and @kisielk

**Comment by kisielk** [comment]
@vishal24tuniki at that point I think you might as well make another package hosted separately, and we can link it from the gorilla/sessions README. That way people using this package and continue to use it without having to worry about API changes, and people who want to transition to another package or get the cluster functionality can use the other one. I think it's small enough that it shouldn't be a major effort to do that.

**Comment by elithrar** [comment]
Agree with @kisielk here. A separate lib makes sense given the lightweight
nature.

**Comment by boj** [comment]
Thanks for your input everyone. Closing this in favor of making a separate library.

**Pull request closed without merging**
